CREATE INDEX events_type_time_idx ON event.events(event_type,recorded_at);
CREATE INDEX events_occurred_idx ON event.events(occurred_at);
CREATE INDEX events_agent_time_idx ON event.events(agent_id,recorded_at);
CREATE INDEX events_session_sequence_idx ON event.events(session_id,sequence_number);
CREATE INDEX event_links_target_idx ON event.event_links(target_event_id,target_recorded_at);
CREATE INDEX entities_type_idx ON memory.entities(entity_type);
CREATE INDEX entities_name_trgm_idx ON memory.entities USING gin(canonical_name gin_trgm_ops);
CREATE INDEX entity_aliases_alias_trgm_idx ON memory.entity_aliases USING gin(alias gin_trgm_ops);
CREATE INDEX observations_event_idx ON memory.observations(event_id,event_recorded_at);
CREATE INDEX episode_events_event_idx ON memory.episode_events(event_id,event_recorded_at);
CREATE INDEX facts_subject_predicate_idx ON knowledge.facts(subject_entity_id,predicate);
CREATE INDEX facts_object_predicate_idx ON knowledge.facts(object_entity_id,predicate);
CREATE INDEX facts_active_idx ON knowledge.facts(subject_entity_id,predicate) WHERE status='active';
CREATE INDEX assertions_subject_predicate_idx ON knowledge.assertions(subject_entity_id,predicate);
CREATE INDEX assertions_object_predicate_idx ON knowledge.assertions(object_entity_id,predicate);
CREATE INDEX assertions_source_idx ON knowledge.assertions(source_id);
CREATE INDEX assertions_event_idx ON knowledge.assertions(event_id,event_recorded_at);
CREATE INDEX operations_agent_time_idx ON cognition.operations(agent_id,started_at);
CREATE INDEX operations_status_idx ON cognition.operations(status);
CREATE INDEX working_memory_agent_idx ON cognition.working_memory(agent_id,updated_at);
CREATE INDEX tasks_plan_status_idx ON planning.tasks(plan_id,status);
CREATE INDEX tasks_active_idx ON planning.tasks(status) WHERE status IN('pending','running','blocked');
CREATE INDEX executions_task_idx ON execution.executions(task_id,status);
CREATE INDEX tool_calls_action_idx ON execution.tool_calls(action_id,status);
CREATE INDEX retrieval_chunks_document_idx ON retrieval.chunks(document_id,sequence_number);
CREATE INDEX embeddings_object_idx ON embedding.embeddings(object_type,object_id);
CREATE INDEX embeddings_model_idx ON embedding.embeddings(model_id);
CREATE INDEX embeddings_vector_cosine_idx ON embedding.embeddings USING hnsw(vector vector_cosine_ops);
CREATE INDEX projections_source_idx ON projection.projections(source_type,source_id);
CREATE INDEX graph_edges_from_idx ON graph.edges(from_node_id,relation);
CREATE INDEX graph_edges_to_idx ON graph.edges(to_node_id,relation);
CREATE INDEX network_delivery_pending_idx ON network.event_delivery(status,created_at) WHERE status='pending';
CREATE INDEX llm_calls_operation_idx ON telemetry.llm_calls(operation_id,created_at);
CREATE INDEX security_grants_identity_idx ON security.grants(identity_id,domain_id);
CREATE INDEX security_authority_object_idx ON security.authority_records(object_type,object_id);
